FROM node:18 AS deps
WORKDIR /app
COPY ["package.json", "yarn.lock", ".npmrc", "./"]
COPY apps apps
COPY packages packages
RUN find apps -not -name "package.json" -not -name ".npmrc" -mindepth 2 -maxdepth 2 -print | xargs rm -rf
RUN find packages -not -name "package.json" -not -name ".npmrc" -mindepth 2 -maxdepth 2 -print | xargs rm -rf
RUN cd apps/api && ls
FROM node:18 as installations
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY --from=deps /app .
RUN yarn install --production=false --frozen-lockfile

FROM node:18
WORKDIR /app
COPY --from=installations /app .
RUN npm install pm2 -g
ARG PORT=3000


ENV NODE_ENV=production
ENV PORT=${PORT}
COPY . .
RUN apk add --no-cache libc6-compat
RUN yarn build --scope=api 
WORKDIR /app/apps/api

EXPOSE ${PORT}
CMD [ "pm2-runtime", "start", "npm", "--", "start" ]